spring:
    profiles: test
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:testdb
        username: sa
        password: sa
    jpa:
        hibernate:
            format_sql: true
            use_sql_comments: true
            dialect: org.hibernate.dialect.H2Dialect
            default_schema: barbershop_db_java
            jdbc:
            time_zone: UTC